# Generated by Django 2.1 on 2022-05-09 23:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_incidencia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaIncidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Causa Incidencia',
                'verbose_name_plural': 'Causas Incidencias',
            },
        ),
        migrations.CreateModel(
            name='Compensacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('numero', models.IntegerField(verbose_name='Cantidad')),
                ('montoUnitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Unitario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='imagen_base64',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='created_at_original',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='modificacion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='causa_incidencia',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Credencial', to='people.CausaIncidencia'),
            preserve_default=False,
        ),
    ]
