# Generated by Django 4.2.2 on 2024-05-28 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20240503_1829'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crede_api', '0002_alter_visitante_clave_alter_visitante_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='-', max_length=150)),
                ('descripcion', models.CharField(default='-', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='-', max_length=150)),
                ('descripcion', models.CharField(default='-', max_length=150)),
                ('fecha_compra', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='-', max_length=150)),
                ('observaciones', models.CharField(default='-', max_length=150)),
                ('serie', models.CharField(default='-', max_length=150)),
                ('marca', models.CharField(default='-', max_length=150)),
                ('modelo', models.CharField(default='-', max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_baja', models.DateTimeField(null=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(null=True, upload_to='equipos/%Y/%m/%d')),
                ('ingreso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crede_api.tipoingreso')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crede_api.tipoequipo')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaSalidaEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DateTimeField(auto_now_add=True)),
                ('salida', models.DateTimeField(null=True)),
                ('observaciones', models.CharField(default='-', max_length=150)),
                ('imagen', models.ImageField(null=True, upload_to='ingreso_equipos/%Y/%m/%d')),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crede_api.equipo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_retiro', models.DateTimeField(null=True)),
                ('observaciones', models.CharField(default='-', max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crede_api.equipo')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.person')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
