# Generated by Django 2.1 on 2022-06-29 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multi_email_field.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Área Interna',
                'verbose_name_plural': 'Areas Internas',
            },
        ),
        migrations.CreateModel(
            name='AreaOrganigrama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('areaInterna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='AreaInterna', to='people.AreaInterna')),
            ],
            options={
                'verbose_name': 'Área Organigrama',
                'verbose_name_plural': 'Areas Organigrama',
            },
        ),
        migrations.CreateModel(
            name='Bajas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Baja',
                'verbose_name_plural': 'Bajas',
            },
        ),
        migrations.CreateModel(
            name='CausaIncidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Causa Incidencia',
                'verbose_name_plural': 'Causas Incidencias',
            },
        ),
        migrations.CreateModel(
            name='ClavePuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Clave de Puesto',
                'verbose_name_plural': 'Claves de Puesto',
            },
        ),
        migrations.CreateModel(
            name='Compensacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('numero', models.IntegerField(verbose_name='Cantidad')),
                ('montoUnitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Unitario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compensaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compensacion',
                'verbose_name_plural': 'Compensaciones',
            },
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Contratación',
                'verbose_name_plural': 'Contrataciones',
            },
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('areaPpal', models.CharField(max_length=200)),
                ('areaSecon', models.CharField(max_length=200)),
                ('matricula', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('printed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntidadFederativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Entidad Federativa',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Filiacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('filiacion', models.CharField(blank=True, max_length=255, verbose_name='Filiación')),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('clavepuesto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.ClavePuesto', verbose_name='Clave de Puesto')),
            ],
            options={
                'verbose_name': 'Filiación',
                'verbose_name_plural': 'Filiaciones',
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(null=True, upload_to='Incidencias//%Y/%m/%d')),
                ('created_at_original', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.BooleanField(blank=True, default=False, null=True)),
                ('causa_incidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Credencial', to='people.CausaIncidencia')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'permissions': (('ver_incidencias', 'Puede ver Incidencias'),),
            },
        ),
        migrations.CreateModel(
            name='InfoPersonalAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Sueldo')),
                ('despensa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ayuda de Despensa (38)')),
                ('prevision', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Previsión Social Múltiple (44)')),
                ('servicios', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ayuda por Servicios (46)')),
                ('compensacion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Compensación Garantizada (06)')),
                ('sueldo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Sueldo Total')),
                ('sueldo_neto_nivel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Sueldo Neto Nivel')),
                ('sueldo_neto_trab', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Sueldo Neto Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='NivelSueldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nivel Sueldo',
                'verbose_name_plural': 'Niveles de Sueldos',
            },
        ),
        migrations.CreateModel(
            name='Nombramiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nombramiento',
                'verbose_name_plural': 'Nombramientos',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=255, verbose_name='Mátricula')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=255, verbose_name='Apellido Paterno')),
                ('apellido2', models.CharField(max_length=255, verbose_name='Apellido Materno')),
                ('puesto', models.CharField(max_length=255, verbose_name='Puesto')),
                ('curp', models.CharField(max_length=255, verbose_name='CURP')),
                ('rfc', models.CharField(max_length=255, verbose_name='RFC')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('municipio', models.CharField(max_length=255, verbose_name='Municipio')),
                ('cp', models.CharField(max_length=255, verbose_name='Código Postal')),
                ('colonia', models.CharField(max_length=255, verbose_name='Colonia')),
                ('nombre_via', models.CharField(max_length=255, verbose_name='Calle')),
                ('num_exterior', models.CharField(max_length=255, verbose_name='Número Ext.')),
                ('num_interior', models.CharField(max_length=255, verbose_name='Número Int.')),
                ('email_personal', models.CharField(max_length=255, verbose_name='Correo electrónico')),
                ('email_institucional', multi_email_field.fields.MultiEmailField(blank=True, default=[], verbose_name='Correo(s) institucional')),
                ('extension_telefonica', models.CharField(blank=True, max_length=255, verbose_name='Extensión telefónica')),
                ('telefono1', models.CharField(max_length=14, verbose_name='Teléfono de Contacto 1')),
                ('telefono2', models.CharField(max_length=14, verbose_name='Teléfono de Contacto 2')),
                ('emergencia_contacto', models.CharField(max_length=255, verbose_name='A quien llamar en caso de emergencia')),
                ('emergencia_telefono', models.CharField(max_length=14, verbose_name='Teléfono Emergencia')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='persona/%Y/%m/%d')),
                ('imagen_base64', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('areaInterna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.AreaInterna', verbose_name='Área Interna')),
                ('cat_area_org', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='areaInterna', chained_model_field='areaInterna', null=True, on_delete=django.db.models.deletion.CASCADE, to='people.AreaOrganigrama', verbose_name='Área Organigrama')),
                ('cat_contratacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.Contratacion', verbose_name='Contratación')),
                ('cat_entidades_federativas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.EntidadFederativa', verbose_name='Estado')),
                ('cat_filiacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Filiacion', verbose_name='Filiación')),
                ('cat_horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Horarios', verbose_name='Horario')),
                ('cat_nombramiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Nombramiento', verbose_name='Tipo de Nombramiento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'permissions': (('datos_personales', 'Puede ver datos personales'), ('tomar_fotografia', 'Puede tomar fotografía'), ('imprimir_credencial', 'Puede imprimir credencial'), ('dar_baja', 'Puede dar de baja')),
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='TipoRelacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Relación',
                'verbose_name_plural': 'Tipo de Relaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoVia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Vía',
                'verbose_name_plural': 'Tipo de Vías',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='cat_tipo_via',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.TipoVia', verbose_name='Tipo de vía'),
        ),
        migrations.AddField(
            model_name='person',
            name='emergencia_cat_relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.TipoRelacion', verbose_name='Parentesco o relación'),
        ),
        migrations.AddField(
            model_name='infopersonaladd',
            name='cat_nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Nivel', verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='infopersonaladd',
            name='cat_nombramiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Nombramiento', verbose_name='Tipo de Nombramiento'),
        ),
        migrations.AddField(
            model_name='infopersonaladd',
            name='cat_sueldo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.NivelSueldo', verbose_name='Nivel de Sueldo'),
        ),
        migrations.AddField(
            model_name='infopersonaladd',
            name='info_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.Person'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='matriculaCredencial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Credencial', to='people.Person'),
        ),
        migrations.AddField(
            model_name='compensaciones',
            name='info_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.Person'),
        ),
        migrations.AddField(
            model_name='bajas',
            name='info_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.Person'),
        ),
    ]
