# Generated by Django 2.1 on 2022-06-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compensacion',
            options={'verbose_name': 'Actividad Compensación', 'verbose_name_plural': 'Actividades de Compensación'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('datos_personales', 'Puede ver datos personales'), ('tomar_fotografia', 'Puede tomar fotografía'), ('imprimir_credencial', 'Puede imprimir credencial'), ('dar_baja', 'Puede dar de baja'), ('modificar_directorio', 'Puede modificar directorio')), 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AddField(
            model_name='compensacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='compensaciones',
            name='compensacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Compensacion'),
        ),
        migrations.AddField(
            model_name='person',
            name='clave_presupuestal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Clave Presupuestal'),
        ),
        migrations.AddField(
            model_name='person',
            name='comision_sindical',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
