# Generated by Django 2.1 on 2022-07-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20220629_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='horario_finde',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Horario Fin de Semana'),
        ),
    ]
