# Generated by Django 2.1 on 2022-11-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20220726_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='telefono2',
            field=models.CharField(blank=True, max_length=14, verbose_name='Teléfono de Contacto 2'),
        ),
    ]
