# Generated by Django 2.1 on 2023-01-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20221103_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_update_vacaciones',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='vacaciones_extra',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Vacaciones extraordinarias'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telefono2',
            field=models.CharField(max_length=14, verbose_name='Teléfono de Contacto 2'),
        ),
    ]
