# Generated by Django 4.2.2 on 2023-10-31 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20230122_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayudas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, verbose_name='User')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montoXDia', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Unitario')),
                ('info_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.person')),
            ],
            options={
                'verbose_name': 'Ayuda',
                'verbose_name_plural': 'Ayudas',
            },
        ),
        migrations.CreateModel(
            name='PersonaAyuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True)),
                ('servicio', models.CharField(max_length=255, verbose_name='Servicio')),
                ('destino', models.CharField(max_length=255, verbose_name='Destino')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ayuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ayudas')),
            ],
            options={
                'verbose_name': 'Persona con acceso a Ayuda',
                'verbose_name_plural': 'Personas con Ayudas',
                'permissions': (('asignar_ayudas', 'Puede asignar ayudas'),),
            },
        ),
        migrations.CreateModel(
            name='ServicioSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sangre', models.CharField(max_length=14, verbose_name='Tipo de Sangre')),
                ('escuela_procedencia', models.CharField(max_length=255, verbose_name='Escuela de Procedencia')),
                ('escuela_domicilio', models.CharField(max_length=255, verbose_name='Domicilio de la Escuela')),
                ('carrera', models.CharField(max_length=255, verbose_name='Carrera o Especialidad')),
                ('creditos_cursados', models.CharField(max_length=20, verbose_name='Total de Créditos Cursados')),
                ('numero_matricula', models.CharField(max_length=20, verbose_name='Número de Matrícula')),
                ('telefono_escuela', models.CharField(max_length=14, verbose_name='Teléfono de la Escuela')),
                ('periodo', models.CharField(max_length=255, verbose_name='Periodo en el que se realizará el Servicio')),
                ('horario', models.CharField(max_length=255, verbose_name='Horario de desempeño de las actividades')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='Actividades')),
                ('info_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
            options={
                'verbose_name': 'Servicio social',
                'verbose_name_plural': 'Servicios sociales',
                'permissions': (('servicio_social', 'Puede ver, crear y editar servicios sociales'),),
            },
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.personaayuda')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleOrganigrama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areasInternas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='multiples_areas', to='people.areainterna')),
                ('info_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.person')),
            ],
        ),
    ]
