# Generated by Django 4.2.13 on 2024-05-20 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250)),
                ('department', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('matricula', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employee-avatars/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_end', models.DateTimeField(null=True)),
            ],
        ),
    ]
